-- Insert sample skincare categories
INSERT INTO public.categories (name, description, image_url) VALUES 
('Cleansers', 'Deep cleansing formulas for all skin types', '/api/placeholder/300/200'),
('Serums', 'Concentrated treatments for targeted concerns', '/api/placeholder/300/200'),
('Moisturizers', 'Hydrating formulas for healthy skin barrier', '/api/placeholder/300/200'),
('Sunscreens', 'Daily protection from harmful UV rays', '/api/placeholder/300/200'),
('Masks', 'Intensive treatments for weekly skincare', '/api/placeholder/300/200'),
('Toners', 'Balancing and prep formulas', '/api/placeholder/300/200');

-- Insert sample skincare products
INSERT INTO public.products (
  name, 
  description, 
  short_description, 
  price, 
  original_price, 
  category_id, 
  brand, 
  image_url, 
  images, 
  ingredients, 
  skin_types, 
  benefits, 
  rating, 
  review_count, 
  stock_quantity, 
  is_featured
) VALUES 
(
  'Vitamin C Brightening Serum',
  'A powerful antioxidant serum that brightens skin tone, reduces dark spots, and protects against environmental damage. Formulated with 20% L-Ascorbic Acid and Vitamin E for maximum potency and stability.',
  'Brightening serum with 20% Vitamin C for radiant skin',
  7900,
  9900,
  (SELECT id FROM categories WHERE name = 'Serums' LIMIT 1),
  'GlowAI Labs',
  '/api/placeholder/400/400',
  ARRAY['/api/placeholder/400/400', '/api/placeholder/400/400', '/api/placeholder/400/400'],
  ARRAY['L-Ascorbic Acid', 'Vitamin E', 'Hyaluronic Acid', 'Ferulic Acid'],
  ARRAY['Normal', 'Dry', 'Combination'],
  ARRAY['Brightening', 'Anti-aging', 'Antioxidant Protection'],
  4.8,
  324,
  50,
  true
),
(
  'Hyaluronic Acid Hydrating Serum',
  'Ultra-hydrating serum with multiple molecular weights of hyaluronic acid to plump and moisturize skin at every level. Perfect for dehydrated and aging skin.',
  'Multi-molecular hyaluronic acid for deep hydration',
  6500,
  8500,
  (SELECT id FROM categories WHERE name = 'Serums' LIMIT 1),
  'GlowAI Labs',
  '/api/placeholder/400/400',
  ARRAY['/api/placeholder/400/400', '/api/placeholder/400/400'],
  ARRAY['Sodium Hyaluronate', 'Hyaluronic Acid', 'Glycerin', 'Panthenol'],
  ARRAY['All Skin Types'],
  ARRAY['Hydration', 'Plumping', 'Anti-aging'],
  4.9,
  567,
  75,
  true
),
(
  'Gentle Foam Cleanser',
  'A pH-balanced foam cleanser that removes impurities without stripping the skin. Enriched with ceramides and niacinamide for healthy skin barrier support.',
  'Gentle pH-balanced cleanser for daily use',
  3200,
  NULL,
  (SELECT id FROM categories WHERE name = 'Cleansers' LIMIT 1),
  'GlowAI Labs',
  '/api/placeholder/400/400',
  ARRAY['/api/placeholder/400/400', '/api/placeholder/400/400'],
  ARRAY['Sodium Cocoyl Isethionate', 'Ceramides', 'Niacinamide', 'Glycerin'],
  ARRAY['Normal', 'Sensitive', 'Combination'],
  ARRAY['Gentle Cleansing', 'Barrier Support', 'Oil Control'],
  4.7,
  234,
  100,
  false
),
(
  'Retinol Night Serum',
  'A gentle yet effective retinol serum that promotes cell turnover and reduces signs of aging. Formulated with 0.5% encapsulated retinol and soothing botanicals.',
  'Anti-aging retinol serum for overnight renewal',
  8900,
  11900,
  (SELECT id FROM categories WHERE name = 'Serums' LIMIT 1),
  'GlowAI Labs',
  '/api/placeholder/400/400',
  ARRAY['/api/placeholder/400/400', '/api/placeholder/400/400', '/api/placeholder/400/400'],
  ARRAY['Encapsulated Retinol', 'Squalane', 'Centella Asiatica', 'Vitamin E'],
  ARRAY['Normal', 'Mature', 'Combination'],
  ARRAY['Anti-aging', 'Smoothing', 'Pore Refinement'],
  4.6,
  189,
  30,
  true
),
(
  'Ceramide Daily Moisturizer',
  'Rich, nourishing moisturizer with essential ceramides and hyaluronic acid. Restores and maintains the skin barrier for healthy, hydrated skin all day.',
  'Barrier-restoring moisturizer with ceramides',
  4500,
  NULL,
  (SELECT id FROM categories WHERE name = 'Moisturizers' LIMIT 1),
  'GlowAI Labs',
  '/api/placeholder/400/400',
  ARRAY['/api/placeholder/400/400', '/api/placeholder/400/400'],
  ARRAY['Ceramide NP', 'Ceramide AP', 'Hyaluronic Acid', 'Cholesterol'],
  ARRAY['Dry', 'Normal', 'Sensitive'],
  ARRAY['Hydration', 'Barrier Repair', 'Soothing'],
  4.8,
  445,
  80,
  false
),
(
  'Niacinamide Pore Control Serum',
  'A targeted serum with 10% niacinamide to minimize pores, control oil production, and improve skin texture. Perfect for oily and acne-prone skin.',
  '10% niacinamide for pore control and oil regulation',
  5500,
  7000,
  (SELECT id FROM categories WHERE name = 'Serums' LIMIT 1),
  'GlowAI Labs',
  '/api/placeholder/400/400',
  ARRAY['/api/placeholder/400/400', '/api/placeholder/400/400'],
  ARRAY['Niacinamide', 'Zinc PCA', 'Salicylic Acid', 'Witch Hazel'],
  ARRAY['Oily', 'Combination', 'Acne-Prone'],
  ARRAY['Pore Minimizing', 'Oil Control', 'Texture Improvement'],
  4.7,
  298,
  60,
  true
),
(
  'SPF 50 Mineral Sunscreen',
  'Broad-spectrum mineral sunscreen with zinc oxide and titanium dioxide. Lightweight, non-greasy formula that provides superior protection without white cast.',
  'Mineral sunscreen with no white cast',
  3800,
  NULL,
  (SELECT id FROM categories WHERE name = 'Sunscreens' LIMIT 1),
  'GlowAI Labs',
  '/api/placeholder/400/400',
  ARRAY['/api/placeholder/400/400', '/api/placeholder/400/400'],
  ARRAY['Zinc Oxide', 'Titanium Dioxide', 'Squalane', 'Vitamin E'],
  ARRAY['All Skin Types'],
  ARRAY['UV Protection', 'Non-comedogenic', 'Water Resistant'],
  4.9,
  512,
  120,
  false
),
(
  'AHA/BHA Exfoliating Toner',
  'Gentle chemical exfoliant with glycolic acid and salicylic acid to remove dead skin cells and unclog pores. Reveals smoother, brighter skin.',
  'Chemical exfoliant for smooth, radiant skin',
  4200,
  5500,
  (SELECT id FROM categories WHERE name = 'Toners' LIMIT 1),
  'GlowAI Labs',
  '/api/placeholder/400/400',
  ARRAY['/api/placeholder/400/400', '/api/placeholder/400/400'],
  ARRAY['Glycolic Acid', 'Salicylic Acid', 'Witch Hazel', 'Aloe Vera'],
  ARRAY['Normal', 'Oily', 'Combination'],
  ARRAY['Exfoliation', 'Pore Cleansing', 'Brightening'],
  4.5,
  167,
  90,
  false
);